{% set name = "smokescreen" %}
{% set version = "1.3.0" %}

package:
  name: lsstdesc-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smokescreen-{{ version }}.tar.gz
  sha256: cfa23afc02b1c89b41485f3c686cda21ef715f75e06fd7d6ae4477f8990f74a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - astropy >=5.3.0
    - sacc >=0.12
    - pyccl >=3.0.2
    - jsonargparse >=4.0
    - cosmosis >=2.5
    - fitsio
    - firecrown
    - cosmosis-build-standard-library

test:
  imports:
    - smokescreen
  # no pip check since it is broken
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/LSSTDESC/Smokescreen
  summary: 'Smokescreen: DESC Blinding Unified Library. Based on the Muir et al. (2021) data-vector blinding method.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
